baseURL = "https://kalmyfi.github.io/sivutv2/"
languageCode = "fi-fin"
title = "Kalmy Ry"
theme = "hugo-arcana"
copyright = "© Kalmy Ry."


[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false

    
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/groups/199178809406494"



    [params.footer]

        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
