[[main]]
    name = "Kokoukset"
    weight = 30
[[main]]
    parent = "Kokoukset"
    name = "Talvikokous 2025"
    weight = 31
[[main]]
    parent = "Kokoukset"
    name = "Kesäkokous 2024"
    weight = 32
[[main]]
    parent = "Kokoukset"
    name = "Pöytäkirjat"
    weight = 33
[[main]]
    parent = "Metsästys"
    name = "Kauriinpyynti 24/25"
    weight = 11
[[main]]
    parent = "Metsästys"
    name = "Hirvenpyynti 24"
    identifier = "sub-lorem"
    weight = 12
[[main]]
    parent = "Metsästys"
    name = "Tilastot"
    weight = 13
[[main]]
    parent = "Metsästys"
    name = "Vieraskortit"
    weight = 14
[[main]]
    parent = "Metsästys"
    name = "Saaliskiintiöt"
    weight = 15
[[main]]
    parent = "Metsästys"
    name = "Koemaastot"
    weight = 10
