[[main]]
    name = "Kokoukset"
    weight = 30
[[main]]
    parent = "Kokoukset"
    name = "Talvikokous 2025"
    url = '/talvikokous2025'
    weight = 31
[[main]]
    parent = "Kokoukset"
    name = "Kesäkokous 2024"
    url = '/kesakokous2024'
    weight = 32
[[main]]
    parent = "Kokoukset"
    name = "Pöytäkirjat"
    weight = 33
[[main]]
    name = "Metsästys"
    identifier = "Metsästys" 
    weight = 80
[[main]]
    parent = "Metsästys"
    name = "Kauriinpyynti 24/25"
    url = '/kauriinpyynti'
    weight = 80
[[main]]
    parent = "Metsästys"
    name = "Hirvenpyynti 24"
    url = '/hirvenpyynti'
    weight = 81
[[main]]
    parent = "Metsästys"
    name = "Tilastot"
    weight = 82
[[main]]
    parent = "Metsästys"
    name = "Vieraskortit"
    url = '/vieraskortit'
    weight = 83
[[main]]
    parent = "Metsästys"
    name = "Saaliskiintiöt"
    url = '/saaliskiintio'
    weight = 84
[[main]]
    parent = "Metsästys"
    name = "Koemaastot"
    url = '/koemaastot'
    weight = 85
