[[main]]
    name = "Kokoukset"
    identifier = "Kokoukset"
    url = '/poytakirjat'
    weight = 30
[[main]]
    name = "Metsästys"
    identifier = "Metsästys"
    weight = 80
[[main]]
    parent = "Metsästys"
    name = "Hirvenpyynti"
    url = '/hirvenpyynti'
    weight = 81
[[main]]
    parent = "Metsästys"
    name = "Kauriinpyynti"
    url = '/kauriinpyynti'
    weight = 82
[[main]]
    parent = "Metsästys"
    name = "Tilastot"
    url = '/tilastot'
    weight = 83
[[main]]
    parent = "Metsästys"
    name = "Vieraskortit"
    url = '/vieraskortit'
    weight = 84
[[main]]
    parent = "Metsästys"
    name = "Saaliskiintiöt"
    url = '/saaliskiintio'
    weight = 85
[[main]]
    parent = "Metsästys"
    name = "Metsästysalueet"
    url = '/koemaastot'
    weight = 86
